### ISSUE TITLE
2021.06.12

### ISSUE THREAD

**Issue by vivabin** [ready-techie/daily-Retrospective#3]
`Done`
스터디 카페에서 알고리즘 풀이 (프로그래머스 h-index)

`Do` 
레디테키 스크립트 준비 

`Good` 
다시 스터디 카페에 왔다.

`Bad` 
쉬는날이되면 더 집중을 못한다. => 목표를 재정립 하자

**Comment by wooooooood** [comment]
`Done`
사이드 프로젝트 스터디 모임! 거의 하루종일.

`Good`
간만에 코딩을 즐겁게..? 한듯

`Bad`
시간 착각해서 한시간 일찍 갔는데 코딩 안하고 놀았다ㅠ
스터디를 하는 날은 할만큼 했다고 생각하고 더이상 안하는거같은데 이런 생각을 버려야 한다
